name: CMake-64

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-2019
    env:
      BUILD_TYPE: Release
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
      with:
        repository: gmh5225/grpc
        ref: master
        submodules: 'recursive'
  
    - name: Build
      run: |
        md .build
        cd .build
        cmake .. -DgRPC_BUILD_TESTS=OFF -DCMAKE_INSTALL_PREFIX=grpc_install
        cmake --build . --config ${{ env.BUILD_TYPE }}
        cmake --install ../.build
        
    - name: Upload artifacts
      uses: actions/upload-artifact@main
      with:
        name: grpc-64
        path: |
          .build/grpc_install/*

    - name: archive
      run:
        7z a grpc-64-gmh.zip .build/grpc_install/*
    
    - name: Release
      uses: softprops/action-gh-release@v1
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      with:
        prerelease: ${{ !startsWith(github.ref, 'refs/tags/v') || contains(github.ref, '-pre') }}
        files: grpc-64-gmh.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
        
